services:
  - type: web
    name: doit-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        required: true
      - key: JWT_SECRET
        generateValue: true
    plan: free

  - type: web
    name: doit-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: "./frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        required: true
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    plan: free